CORE-123 changes for review stage

diff --git a/.github/workflows/pr-review-pipeline.yml b/.github/workflows/pr-review-pipeline.yml
--- a/.github/workflows/pr-review-pipeline.yml
+++ b/.github/workflows/pr-review-pipeline.yml
@@ -22,6 +22,8 @@ jobs:
 
     steps:
       - uses: actions/checkout@v5
+        with:
+          fetch-depth: 0
 
       - uses: actions/setup-java@v5
         with:
@@ -61,6 +63,8 @@ jobs:
 
     steps:
       - uses: actions/checkout@v5
+        with:
+          fetch-depth: 0
 
       - name: Download Updated Pom
         uses: actions/download-artifact@v5
@@ -89,6 +93,8 @@ jobs:
 
     steps:
       - uses: actions/checkout@v5
+        with:
+          fetch-depth: 0
 
       - name: Download Updated Pom
         uses: actions/download-artifact@v5
@@ -103,17 +109,27 @@ jobs:
 
       - name: Analyze with SonarQube (Manual PR Parameters)
         env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+          SONAR_TOKEN: ${{ secrets.GIT_SONAR_TOKEN }}
+          PROJECT_KEY: ${{ secrets.PROJECT_KEY }}
         run: |
+          if [ -z "$SONAR_TOKEN" ]; then
+            echo "SONAR_TOKEN is missing"
+            exit 1
+          fi
+
+          if [ -z "$PROJECT_KEY" ]; then
+            echo "PROJECT_KEY is missing"
+            exit 1
+          fi
+
           mvn clean verify sonar:sonar \
-            -Dsonar.projectKey=${{ secrets.PROJECT_KEY }} \
+            -Dsonar.projectKey="$PROJECT_KEY" \
             -Dsonar.organization=devops-champ \
             -Dsonar.host.url=https://sonarcloud.io \
             -Dsonar.pullrequest.key=${{ github.event.pull_request.number }} \
             -Dsonar.pullrequest.branch=$GITHUB_HEAD_REF \
             -Dsonar.pullrequest.base=$GITHUB_BASE_REF \
-            -Dsonar.token=$SONAR_TOKEN
+            -Dsonar.token="$SONAR_TOKEN"
 
   docker:
     runs-on: ubuntu-latest
@@ -127,6 +143,8 @@ jobs:
 
     steps:
       - uses: actions/checkout@v5
+        with:
+          fetch-depth: 0
 
       - name: Build Docker Image
         run: |
